name: Graph React App

on:
    push:
        branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20'
  
        - name: install dependencies
          run: npm ci
  
        - name: Print debugging information
          run: | 
            echo "Node Version: $(node --version)"
            echo "NPM Version: $(npm --version)"
            echo "Wroking Directory: $(pwd)"
            echo "Contents of Working Directory: $(ls -l)"
            echo "Contents of node_modules: $(ls -l node_modules)"
